pipeline {
    // this define use agent whatever available
    agent any 
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'whoami'
            }
        }
    }
}
