pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M398"
    }

    stages {
      stage('mvn version print') {
            steps {
              sh 'echo "print version"'
              sh 'mvn --version'
            }
        }
    }
}